Repository awslabs/sagemaker-debugger, pull requests merged in 2019-12, with the labels that each got.

#80 Replace aioboto3 with boto3
  setup.py
  smdebug/core/access_layer/s3handler.py
  smdebug/core/access_layer/utils.py
  smdebug/core/index_reader.py
  smdebug/core/s3_utils.py
  smdebug/trials/s3_trial.py
  tests/analysis/utils.py
  tests/core/test_handler.py
Labels: enhancement

#97 cleaned up examples folder a bit
  examples/mxnet/README.md
  examples/mxnet/notebooks/mxnet-tensor-plot.ipynb
  examples/mxnet/notebooks/tensor_plot.py
  examples/mxnet/notebooks/tensorplot.gif
  examples/mxnet/scripts/mnist_gluon_all_zero_demo.py
  examples/mxnet/scripts/mnist_gluon_block_input_output_demo.py
  examples/mxnet/scripts/mnist_gluon_model_input_output_demo.py
  examples/mxnet/scripts/mnist_gluon_realtime_visualize_demo.py
  examples/mxnet/scripts/mnist_gluon_save_all_demo.py
  examples/mxnet/scripts/mnist_mxnet.py
  examples/mxnet/scripts/mnist_mxnet_hvd.py
  examples/mxnet/scripts/mxnet_fashionmnist_w_g_b.py
  examples/pytorch/README.md
  examples/tensorflow/README.md
  tests/mxnet/test_training_end.py
  tests/resources/mxnet/mnist_gluon_basic_hook_demo.py
Labels: documentation

#92 Add docs for MissingCollectionFiles Exception
  docs/analysis.md
Labels: documentation

#106 More doc updates
  README.md
  docs/api.md
  docs/env_var.md
  docs/mxnet.md
  docs/pytorch.md
  docs/sagemaker.md
  docs/sagemaker_api.md
  docs/tensorflow.md
Labels: documentation

#68 Fix writer initialization bug affecting horovod TF
  examples/tensorflow/local/horovod_keras_mnist.py
  examples/tensorflow/local/mnist.py
  examples/tensorflow/local/tf_keras_resnet.py
  examples/tensorflow/sagemaker_byoc/horovod_keras_mnist.py
  examples/tensorflow/sagemaker_byoc/mnist.py
  examples/tensorflow/sagemaker_byoc/simple.py
  examples/tensorflow/sagemaker_byoc/tf_keras_resnet.py
  examples/tensorflow/sagemaker_official_container/horovod_estimator_mnist.py
  examples/tensorflow/sagemaker_official_container/horovod_keras_mnist.py
  examples/tensorflow/sagemaker_official_container/mnist.py
  smdebug/core/config_constants.py
  smdebug/core/hook.py
  smdebug/core/json_config.py
  smdebug/mxnet/hook.py
  smdebug/pytorch/hook.py
  smdebug/tensorflow/base_hook.py
  smdebug/tensorflow/keras.py
  smdebug/tensorflow/session.py
  smdebug/tensorflow/utils.py
  tests/mxnet/test_hook_all_zero.py
  tests/tensorflow/hooks/test_mirrored_strategy.py
  tests/tensorflow/keras/test_keras.py
  tests/tensorflow/test_utils.py
  tests/zero_code_change/README.md
  tests/zero_code_change/horovod/__init__.py
  tests/zero_code_change/horovod/tensorflow/__init__.py
  tests/zero_code_change/horovod/tensorflow/test_estimator.py
  tests/zero_code_change/horovod/tensorflow/test_keras.py
  tests/zero_code_change/horovod/tensorflow/utils.py
Labels: bug

#86 Skip logging the input tensors to the loss block
  smdebug/core/hook.py
  smdebug/mxnet/collection.py
  smdebug/pytorch/collection.py
  tests/core/test_hook_save_scalar.py
  tests/mxnet/test_hook_loss_collection.py
  tests/pytorch/test_loss.py
Labels: bug
